#!/usr/bin/env bash

# This script was generated by Copilot to demonstrate a simple chat completion request.
curl -X POST http://localhost:11434/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "functiongemma:270m",
    "messages": [
      {
        "role": "user",
        "content":"What is the news on politics in Beijing?"
      }
    ]
  }' \
  | jq '.'

# Output example
: << 'EOF'
➜  FunctionGemmaLab git:(main) ✗ ./scripts/completion1.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   665  100   533  100   132    451    111  0:00:01  0:00:01 --:--:--   563
{
  "id": "chatcmpl-590",
  "object": "chat.completion",
  "created": 1766296442,
  "model": "functiongemma:270m",
  "system_fingerprint": "fp_ollama",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "I apologize, but I cannot assist with finding the capital of a country. My current capabilities are focused on assisting with travel planning and information retrieval. I cannot provide information about historical or geographical capitals."
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 17,
    "completion_tokens": 40,
    "total_tokens": 57
  }
}
EOF
